site_name: Python & Microbit
# site_url: https://bdelaup.github.io/
# site_dir: public


site_url: https://bdelaup.github.io/formation-python-snt/
#site_description: Formation Python - Microbit & SNT
#site_author: B. Delaup 

# repo_name: NSI Jules Haag
#repo_url: https://github.com/bdelaup/formation-python-snt
#edit_uri: "https://github.com/bdelaup/formation-python-snt/edit/main/docs/"

copyright: <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licence Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a> Benoit Delaup

theme:
    name: material
    language: fr
    features:
        - navigation.tabs
        - navigation.sections
        - toc.integrate
        - navigation.top
        - search.suggest
        - search.highlight
        - content.tabs.link
        - content.code.annotation
        - content.code.copy   
        
    icon:
      edit: material/pencil 
      view: material/eye
    custom_dir: overrides

nav:

  - Programme : index.md
  - Python : 
    - python_generalite.md
    - python_type.md
    - python_objet.md
  - Microbit : 
    - Description HW : mb_description.md
    - Micropython : mb_upy.md
    - Outils : mb_outils.md

  - Remerciements: remerciements.md

extra_css:
    - site-styles/table.css
    - site-styles/admonitions.css
    - site-styles/formatting.css
    - site-styles/code.css

plugins:
    - search
    - glightbox:
        touchNavigation: true    
    - print-site:
        add_to_navigation: False
        print_page_title: 'Imprimer ...'
        add_print_site_banner: false
        # Table of contents
        add_table_of_contents: true
        toc_title: 'Table des matières'
        toc_depth: 6
        # Content-related
        add_full_urls: true
        enumerate_headings: true
        enumerate_figures: true
        add_cover_page: true
        cover_page_template: ""
        path_to_pdf: ""
        include_css: true
        enabled: true
        exclude:

markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - toc: 
      permalink: true

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - site-js/mathjax.js
  - site-js/tablesort.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
